# Generated by Django 3.2.16 on 2024-05-09 16:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_auto_20240509_0450'),
    ]

    operations = [
        migrations.RenameField(
            model_name='group',
            old_name='tittle',
            new_name='title',
        ),
    ]
